### ISSUE TITLE
Use official versions of `grunt-eslint` and `eslint`

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-project/fluid-grunt-lint-all#14]
(Migrated from an issue created by @jobara in our previous JIRA instance.)

Currently gpii-grunt-lint-all makes use [fluid-grunt-eslint](https://github.com/fluid-project/fluid-grunt-eslint) and conversely [fluid-eslint](https://github.com/fluid-project/fluid-eslint). These packages had been in use to address an issue with reporting of files by the linter (eslint issue [#4931](https://github.com/eslint/eslint/issues/4931)). In recent versions of eslint they have exposed the tooling and, as such, grunt-eslint now supports multiple formatters including "tap" and custom formatters. 

At any rate, using the canonical versions will allow for easier and more frequent future upgrades, better compatibility with linting tools integrated into IDEs and allow for linting files that include modern ECMAScript syntax.

**Comment by jobara** [comment]
Originally filed as [GPII-4503](https://issues.gpii.net/browse/GPII-4503)

**Comment by jobara** [comment]
It seems that we'll have to update [eslint-config-fluid](https://github.com/fluid-project/eslint-config-fluid) to not include valid-jsdoc rules which have been deprecated. I've filed [FLUID-6548](https://issues.fluidproject.org/browse/FLUID-6548) to cover that issue.
